import { NextResponse } from 'next/server';

export async function GET() {
  const data = {
    lob_performance: [
      {
        id: 'fifastra',
        name: 'FIFASTRA',
        active_users: 168480,
        penetration_pct: 72,
        penetration_change: 5,
        funnel_viewed: 234000,
        funnel_applied: 62300,
        funnel_submitted: 38700,
        funnel_disbursed: 19200,
        avg_time_to_disburse: 3.2,
        status: 'on_track' as const,
        cohort_month1: 68,
        cohort_month3: 54,
        cohort_month6: 41,
      },
      {
        id: 'spektra',
        name: 'SPEKTRA',
        active_users: 65520,
        penetration_pct: 28,
        penetration_change: -3,
        funnel_viewed: 234000,
        funnel_applied: 31200,
        funnel_submitted: 12400,
        funnel_disbursed: 4960,
        avg_time_to_disburse: 4.8,
        status: 'below_target' as const,
        cohort_month1: 52,
        cohort_month3: 38,
        cohort_month6: 22,
      },
      {
        id: 'danastra',
        name: 'DANASTRA',
        active_users: 142740,
        penetration_pct: 61,
        penetration_change: 4,
        funnel_viewed: 234000,
        funnel_applied: 52800,
        funnel_submitted: 31200,
        funnel_disbursed: 15600,
        avg_time_to_disburse: 3.8,
        status: 'growing' as const,
        cohort_month1: 71,
        cohort_month3: 60,
        cohort_month6: 48,
      },
      {
        id: 'finatra',
        name: 'FINATRA',
        active_users: 105300,
        penetration_pct: 45,
        penetration_change: 2,
        funnel_viewed: 234000,
        funnel_applied: 41700,
        funnel_submitted: 23100,
        funnel_disbursed: 10400,
        avg_time_to_disburse: 4.1,
        status: 'stable' as const,
        cohort_month1: 74,
        cohort_month3: 65,
        cohort_month6: 55,
      },
      {
        id: 'amitra',
        name: 'AMITRA',
        active_users: 121680,
        penetration_pct: 52,
        penetration_change: 6,
        funnel_viewed: 234000,
        funnel_applied: 46800,
        funnel_submitted: 27300,
        funnel_disbursed: 12800,
        avg_time_to_disburse: 3.5,
        status: 'growing' as const,
        cohort_month1: 65,
        cohort_month3: 50,
        cohort_month6: 39,
      },
    ],
  };
  return NextResponse.json(data);
}
