import { NextResponse } from 'next/server';

export async function GET() {
  const data = {
    recommendations: [
      {
        id: 'rec-1',
        app_id: 'fifada',
        lob_id: null,
        category: 'aso' as const,
        priority: 'high' as const,
        title: 'Address FIFADA Rating Decline',
        description: 'FIFADA rating dropped 0.4★ in 3 days. 60% of negative reviews cite "long branch process" and "slow approval".',
        estimated_impact: '+0.3★ rating improvement within 2 weeks',
        effort: 'medium' as const,
        status: 'pending' as const,
        created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
      },
      {
        id: 'rec-2',
        app_id: null,
        lob_id: 'spektra',
        category: 'funnel' as const,
        priority: 'high' as const,
        title: 'Simplify SPEKTRA Document Upload',
        description: '62% of users who start SPEKTRA application drop at document upload. Current requirement: 6 documents. Recommend: reduce to 3 core documents.',
        estimated_impact: '+2,100 applications/month if drop-off reduced by 40%',
        effort: 'low' as const,
        status: 'pending' as const,
        created_at: new Date(Date.now() - 86400000 * 5).toISOString(),
      },
      {
        id: 'rec-3',
        app_id: 'fifgo',
        lob_id: null,
        category: 'aso' as const,
        priority: 'medium' as const,
        title: 'Update FIFGO App Store Screenshots',
        description: 'Screenshots have not been updated in 6 months. Competitors have updated theirs with video preview and benefit-focused visuals.',
        estimated_impact: '+8% conversion rate improvement',
        effort: 'low' as const,
        status: 'pending' as const,
        created_at: new Date(Date.now() - 86400000 * 7).toISOString(),
      },
      {
        id: 'rec-4',
        app_id: null,
        lob_id: null,
        category: 'engagement' as const,
        priority: 'medium' as const,
        title: 'Cross-Sell Campaign for Single-LoB Users',
        description: '34,821 users have only 1 LoB product. DANASTRA is the most natural cross-sell for FIFASTRA customers.',
        estimated_impact: 'Estimated Rp 4.2B/month incremental disbursement',
        effort: 'medium' as const,
        status: 'pending' as const,
        created_at: new Date(Date.now() - 86400000 * 10).toISOString(),
      },
      {
        id: 'rec-5',
        app_id: null,
        lob_id: null,
        category: 'retention' as const,
        priority: 'medium' as const,
        title: 'SPEKTRA Disbursement SLA Improvement',
        description: 'SPEKTRA Month-2 retention is 52% (benchmark: 60%). 71% of churned users had disbursement delay >5 days.',
        estimated_impact: '+8pts Month-2 retention improvement',
        effort: 'high' as const,
        status: 'pending' as const,
        created_at: new Date(Date.now() - 86400000 * 14).toISOString(),
      },
    ],
  };
  return NextResponse.json(data);
}
